version: '3.0'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - '${APP_PORT}:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - movie-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  movie-data:
